// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"botfb/internal/dao/internal"
)

// internalMessageTemplateDao is internal type for wrapping internal DAO implements.
type internalMessageTemplateDao = *internal.MessageTemplateDao

// messageTemplateDao is the data access object for table message_template.
// You can define custom methods on it to extend its functionality as you wish.
type messageTemplateDao struct {
	internalMessageTemplateDao
}

var (
	// MessageTemplate is globally public accessible object for table message_template operations.
	MessageTemplate = messageTemplateDao{
		internal.NewMessageTemplateDao(),
	}
)

// Fill with you ideas below.
