// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"botfb/internal/dao/internal"
)

// internalReviewDao is internal type for wrapping internal DAO implements.
type internalReviewDao = *internal.ReviewDao

// reviewDao is the data access object for table review.
// You can define custom methods on it to extend its functionality as you wish.
type reviewDao struct {
	internalReviewDao
}

var (
	// Review is globally public accessible object for table review operations.
	Review = reviewDao{
		internal.NewReviewDao(),
	}
)

// Fill with you ideas below.
